"""Add WebhookEvent table

Revision ID: 91420f425c08
Revises: 4fea26b68426
Create Date: 2025-08-24 17:31:09.522836

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '91420f425c08'
down_revision = '4fea26b68426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
